# cache:
# - "c:\\sr" # stack root, short paths == less problems

build: off

before_test:
- choco install -y ghc --version 8.0.1
- refreshenv
- curl -o cabal.zip --insecure --progress-bar https://www.haskell.org/cabal/release/cabal-install-1.24.0.0/cabal-install-1.24.0.0-x86_64-unknown-mingw32.zip
- 7z x -bd cabal.zip
- cabal --version
- cabal update
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe
- stack --version

clone_folder: "c:\\project"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- set http_proxy=localhost:3000
- set https_proxy=localhost:3000
- stack init
- stack setup > nul
- stack build
